### ISSUE TITLE
Not implementederror 

### ISSUE THREAD

**Issue by ankitchandracs** [AxisCommunications/onnx-to-keras#19]
Traceback (most recent call last):
  File "onnx2keras.py", line 642, in <module>
    Fire(main)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "onnx2keras.py", line 633, in main
    model = onnx2keras(onnx.load(infile))
  File "onnx2keras.py", line 621, in onnx2keras
    output_tensors = ops.make_op(node.op_type, inputs, attrs)
  File "onnx2keras.py", line 18, in make_op
    return getattr(self, 'op_' + op_type.lower())(*inputs, **attrs)
  File "onnx2keras.py", line 213, in op_concat
    raise NotImplementedError
NotImplementedError

**Comment by hakanardo** [comment]
This is hopefully solved now. Pleas reopen if not.
