### ISSUE TITLE
TypeError: op_averagepool() got an unexpected keyword argument 'ceil_mode'

### ISSUE THREAD

**Issue by ardamavi** [AxisCommunications/onnx-to-keras#8]
I get this error, can anybody help me?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/name/opt/anaconda3/envs/onnx2keras/lib/python3.6/site-packages/onnx2keras.py", line 554, in onnx2keras
    output_tensors = ops.make_op(node.op_type, inputs, attrs)
  File "/Users/name/opt/anaconda3/envs/onnx2keras/lib/python3.6/site-packages/onnx2keras.py", line 17, in make_op
    return getattr(self, 'op_' + op_type.lower())(*inputs, **attrs)
TypeError: op_averagepool() got an unexpected keyword argument 'ceil_mode'
```
**Versions:**
- Python 3.6.12
- ONNX 1.8.0
- TensorFlow 2.3.1

**Comment by hakanardo** [comment]
None default ceil_mode is not yet supported. To fix it we need to add a ceil_mode parameter with a default value to op_averagepool() and figgure out how to pass it along to keras.layers.AveragePooling2D, and verify that we got all cases correct by adding tests.
