### ISSUE TITLE
TfKerasOperations' object has no attribute 'op_expand'

### ISSUE THREAD

**Issue by anilsathyan7** [AxisCommunications/onnx-to-keras#9]
I got this error during onnx to keras conversion:

```
Traceback (most recent call last):
  File "onnx2keras.py", line 579, in <module>
    Fire(main)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "onnx2keras.py", line 571, in main
    model = onnx2keras(onnx.load(infile))
  File "onnx2keras.py", line 559, in onnx2keras
    output_tensors = ops.make_op(node.op_type, inputs, attrs)
  File "onnx2keras.py", line 17, in make_op
    return getattr(self, 'op_' + op_type.lower())(*inputs, **attrs)
AttributeError: 'TfKerasOperations' object has no attribute 'op_expand'
```
Is this an unsupported operation issue?

**Comment by hakanardo** [comment]
Yes. Can share a minimal pytorch network needing it?
